### ISSUE TITLE
Add support for launching iOS app

### ISSUE THREAD

**Issue by zacwest** [home-assistant/my.home-assistant.io#1]
Set this as a response to `/.well-known/apple-app-site-association` and we can make the iOS app get opened by default. It won't do anything if the app isn't configured to support it, which can happen at some point in the future.

```json
{
  "applinks": {
    "apps": [],
    "details": [
      {
        "appID": "QMQYCKL255.io.robbie.HomeAssistant.dev",
        "paths": [
          "/redirect/*"
        ]
      },
      {
        "appID": "QMQYCKL255.io.robbie.HomeAssistant.beta",
        "paths": [
          "/redirect/*"
        ]
      },
      {
        "appID": "QMQYCKL255.io.robbie.HomeAssistant",
        "paths": [
          "/redirect/*"
        ]
      }
    ]
  }
}
```

**Comment by bramkragten** [comment]
The `my.home-assistant.io` should not be opened in the iOS app right, or we should add the same redirect logic in the app, which we shouldn't I think?

The URL where we link to, like `http://homeassistant.local:8123/_my_redirect/info`, should be opened in the app.

**Comment by balloob** [comment]
iOS won't trigger our app for instance urls as we can't register them. But we can register this url. So what we can do is:

 - Register this url with iOS so that it opens the app
 - iOS app will open this url, re-implement our redirect confirm logic with prompt based on `redirect.json` file, then redirect user to the instance known by the iOS app.
   - Alternative: we allow injecting an instance url via a url param. That way the iOS app can re-use this website.
 - Now when you click an "open docs in instance" button, it will open iOS app and open in configured instance. That would be pretty sweet!

**Comment by zacwest** [comment]
If we want to keep the 'my' page as the central entrypoint, it would probably be best to offer an "open in app" button, perhaps as an alternative to entering the instance URL and in addition to the confirmation screen.

The only downside here is that it's ridiculously difficult to detect if the app is installed, so it would likely need to open `homeassistant://navigate/_my_redirect/whatnot` from the page. There are some third-party tools that try and accomplish having just one link to either open the store or the app, but they're all heuristic-based and blegh. 

Honestly likely that would be a good thing to add, even if we don't set up universal links.

The upside of universal links is that it's a lot more seamless - tap the documentation link, app opens. Is the redirect.json going to get significantly more complicated? It seems like the real logic is in the 'my' integration and the page is just a front for that. Could always create an API hook in the 'my' integration that can allow the app to give the URL that was requested and allow the 'my' integration to decide if it's valid or not.

**Comment by balloob** [comment]
PR opened. I think that it would be just enough for the iOS app to open this in a webview and inject `homeassistant://navigate` as the HA url. We can either check for a JS function injected by iOS app or if the iOS app adds a url param.
