### ISSUE TITLE
Text missing in selector for backups

### ISSUE THREAD

**Issue by wrt54g** [home-assistant/my.home-assistant.io#220]
The text for supervisor backups is missing
![image](https://user-images.githubusercontent.com/85389871/166811855-6010fb68-6be6-4f7f-993a-3994b15ef12e.png)

**Comment by wrt54g** [comment]
The link works fine

**Comment by ludeeus** [comment]
`supervisor_backup` is deprecated, that's why.
use `backups` instead.
https://github.com/home-assistant/my.home-assistant.io/blob/main/redirect.json#L322-L327

**Comment by wrt54g** [comment]
@ludeeus I pressed the M button in the frontend.
