### ISSUE TITLE
OAuth2 Authorize Callback

### ISSUE THREAD

**Issue by Anian-igor** [home-assistant/my.home-assistant.io#262]
Home Assistant 2022.7.5
Supervisor 2022.07.0
Frontend 20220707.1

I have a problem with [OAuth2 Authorize Callback](https://my.home-assistant.io/redirect/oauth/)
I have an error "Invalid parameters given." and opened "Create a link" page
[https://my.home-assistant.io/create-link/?redirect=oauth](https://my.home-assistant.io/create-link/?redirect=oauth)
Only this link have an issue on MY

**Comment by balloob** [comment]
You are not supposed to open this page directly. It's used as a callback configured for OAuth2 integrations like Nest. When used as part of OAuth2 the correct parameters will be added automatically.

**Comment by Anian-igor** [comment]
Yeah. But not.  Home connect applicaion also cannot find. Also I tried with postman - no luck
