### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by QJoly** [home-assistant/my.home-assistant.io#427]
I've got an infinite loading screen on my.home-assistant.io

![2024-02-05_10-16](https://github.com/home-assistant/my.home-assistant.io/assets/82603435/16af7dcc-267b-4591-a300-6ff9c7a9a97e)

I tried on : 
- My smartphone (even on 4G)
- Firefox (laptop)
- Chromium (laptop)

Both browser on normal mode and private navigation. Everything suggests that the site is down, is that true ?

**Comment by QJoly** [comment]
I tested on a remote machine in US (I'm in France) : Same error

![image](https://github.com/home-assistant/my.home-assistant.io/assets/82603435/db7dd838-115b-40d9-b411-c7c691e67df0)

**Comment by Pilliwiddlipillipitit** [comment]
Have the same issue of infinite loading screen. 
My HAOS installation is brand new and I'm a beginner with HA, so maybe I do something wrong.
In configuration.yaml the default_config: is included so my: should run too.
Usually I access it via http://homeassistant.local:8123 so I never used https://my.home-assistant.io/ bevore.
But today I installed the spotify integration which tries to open https://my.home-assistant.io/redirect/oauth. There I have the same infinite loading screen.

Core 2024.1.6
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

**Comment by Pilliwiddlipillipitit** [comment]
> To add context:
> 
>     * No Adblock
> 
>     * I have an error on my console
> 
> 
> ![image](https://private-user-images.githubusercontent.com/82603435/302240417-18821cb5-b90e-42f8-8575-6ffc5e271227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjkwNDgsIm5iZiI6MTcwNzEyODc0OCwicGF0aCI6Ii84MjYwMzQzNS8zMDIyNDA0MTctMTg4MjFjYjUtYjkwZS00MmY4LTg1NzUtNmZmYzVlMjcxMjI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEwMjU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZGI5OTNlNzI0NGMwYjdjYjJiOTVmYzkwYmQ2NjliNjlhN2E2MGNiOWUyNDQxY2ZmOTYxMjNmZTM5NGY1ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DNGwtxPieYA3CVt8pgy_EVTQhVCkFtOiSiFl6qKdlu8)

I have the same error:
Uncaught ReferenceError: Dt is not defined

**Comment by frenck** [comment]
Thanks for reporting! Reverted a change made this morning. A new version has been deployed 👍 

../Frenck

**Comment by Pilliwiddlipillipitit** [comment]
Thank you for this fast action.

> A new version has been deployed

So, but what does it mean for me? Do I have to wait for an new HAOS Update?

**Comment by Pilliwiddlipillipitit** [comment]
Ah, just a YAML update. now it looks good.
