### ISSUE TITLE
Need to update My Home Assistant links for Dashboards and Dashboard Resources

### ISSUE THREAD

**Issue by dorbitbrown** [home-assistant/my.home-assistant.io#430]
The My Home Assistant  links to 
   "Dashboards" (https://my.home-assistant.io/redirect/lovelace_dashboards/) and 
   "Dashboard Resources" (https://my.home-assistant.io/redirect/lovelace_resources/) 
are not working.  My guess is that they should be updated to 
   https://my.home-assistant.io/redirect/lovelace/dashboards/ and 
   https://my.home-assistant.io/redirect/lovelace/resources/ 
respectively.

Examples of the non-functional links are here:
   https://my.home-assistant.io/faq/#404
and elsewhere in the documentation.

BTW, much of the documentation refers to "Configuration > Dashboards > Resources", while it seems "Configuration" has now been replaced by "Settings", and I cannot find anywhere a tab or menu option for "Resources"

**Comment by tjorim** [comment]
> The My Home Assistant links to\n\"Dashboards\" (https://my.home-assistant.io/redirect/lovelace_dashboards/) and\n\"Dashboard Resources\" (https://my.home-assistant.io/redirect/lovelace_resources/)\nare not working. 

They seem to be working for me, could you check again?

**Comment by dorbitbrown** [comment]
Hey, Jorim, thanks for following up.  It's been a while, and I was a novice at the time, but I recall I had changed Settings>System>Network>"The name your instance will have on your network" to "hass1".  After doing so, "http://homeassistant.local:8123/" stopped working and "http://hass1:8123/" started.  Since then I've made numerous changes and done several reinstalls.  I just tried the same change, and "http://homeassistant.local:8123/" did NOT stop working, so of course the links work, just as you say.   Please go ahead and close this.  Thanks again!
